"""Generate the synthetic Side-Scan Sonar demo survey.

Creates ``data/samples/synthetic_sss``: several scenes (pipe, ghost net,
wreck, rock hard-negative, cylinder, debris) rendered with realistic sonar
appearance, labelled SYNTHETIC, each carrying plausible (but fake) survey
metadata with GPS so the map + geolocation features can be demonstrated.

Usage::

    python scripts/generate_synthetic_sss.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import cv2  # noqa: E402
import synth  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent.parent
OUT = ROOT / "data" / "samples" / "synthetic_sss"

SCENES = [
    ("pipe", 11),
    ("ghost_net", 21),
    ("wreck", 31),
    ("rock", 41),
    ("cylinder", 51),
    ("debris", 61),
    ("ghost_net", 22),
]


def main() -> None:
    (OUT / "Images").mkdir(parents=True, exist_ok=True)
    manifest_images: list[str] = []
    gt_list: list[dict] = []
    image_meta: dict[str, dict] = {}

    for i, (kind, seed) in enumerate(SCENES):
        img, gt = synth.render(kind, seed)
        name = f"synthetic_sss_{kind}_{i:02d}.png"
        cv2.imwrite(str(OUT / "Images" / name), img)
        rel = f"Images/{name}"
        manifest_images.append(rel)
        meta = synth.synthetic_metadata(i, kind)
        image_meta[name] = meta
        gt_list.append({"image": rel, "boxes": gt["boxes"], "meta": meta})

    manifest = {
        "id": "synthetic_sss",
        "name": "Synthetic SSS survey (GPS demo)",
        "description": (
            "Synthetically rendered side-scan-style sonar scenes with plausible (fake) GPS metadata — "
            "for demonstrating geolocation, the map, evidence fusion and reporting. "
            "No real-world coordinates or real debris depicted."
        ),
        "synthetic": True,
        "attribution": "Generated by AQUA-SENTINEL scripts/synth.py — not real survey data.",
        "license_note": "Synthetic imagery; no third-party data included.",
        "tags": ["synthetic", "sss", "gps", "detection-gt"],
        "survey_meta": {"name": "Synthetic SSS survey (GPS demo)", "sonar_type": "sss", "preprocess_preset": "light"},
        "images": manifest_images,
        "image_meta": image_meta,
        "ground_truth": gt_list,
    }
    (ROOT / "data" / "samples" / "synthetic_sss.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    (OUT / "README.md").write_text(
        "Synthetic SSS imagery generated by scripts/synth.py. Explicitly NOT real survey data.\n",
        encoding="utf-8",
    )
    print(f"wrote {len(SCENES)} synthetic images to {OUT}")


if __name__ == "__main__":
    main()
